// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// searchSpectra
List searchSpectra(List specExp, NumericMatrix mzRange, NumericVector mz);
RcppExport SEXP _SWATHtoMRM_searchSpectra(SEXP specExpSEXP, SEXP mzRangeSEXP, SEXP mzSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type specExp(specExpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mzRange(mzRangeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mz(mzSEXP);
    rcpp_result_gen = Rcpp::wrap(searchSpectra(specExp, mzRange, mz));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SWATHtoMRM_searchSpectra", (DL_FUNC) &_SWATHtoMRM_searchSpectra, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SWATHtoMRM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
